spring.config.import=optional:file:.env[.properties]
spring.application.name=nutrition-analysis-service
server.port=${SERVER_PORT}

spring.main.banner-mode=off

spring.data.mongodb.uri=${MONGO_URI}

spring.rabbitmq.host=${RABBITMQ_HOST}
spring.rabbitmq.port=${RABBITMQ_PORT}
spring.rabbitmq.username=${RABBITMQ_USERNAME}
spring.rabbitmq.password=${RABBITMQ_PASSWORD}

feed.cost.service.url=${FEED_COST_URL}

jwt.secret=${JWT_SECRET:BovExoSecretKeyParaAvaliacaoTecnicaMuitoSegura2026}
jwt.expiration=${JWT_EXPIRATION:86400000}

nutrition.analysis.username=${NUTRITION_ANALYSIS_USERNAME}
nutrition.analysis.password=${NUTRITION_ANALYSIS_PASSWORD}