spring.application.name=feed-cost-service

spring.datasource.url=jdbc:postgresql://localhost:5433/bovexo_cost
spring.datasource.username=postgres
spring.datasource.password=admin

spring.jpa.hibernate.ddl-auto=none

server.port=8081