spring.config.import=optional:file:.env[.properties]
spring.application.name=authenticator-service
spring.main.banner-mode=off

server.port=${SERVER_PORT}

spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

jwt.secret=${JWT_SECRET}
jwt.expiration=${JWT_EXPIRATION}

seeder.admin.username=${SEEDER_ADMIN_USERNAME}
seeder.admin.password=${SEEDER_ADMIN_PASSWORD}

seeder.guest.username=${SEEDER_GUEST_USERNAME}
seeder.guest.password=${SEEDER_GUEST_PASSWORD}

seeder.nutrition.username=${SEEDER_NUTRITION_USERNAME}
seeder.nutrition.password=${SEEDER_NUTRITION_PASSWORD}